### ISSUE TITLE
404 on https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map

### ISSUE THREAD

**Issue by dimitrius1986** [zqingr/tfjs-yolov3#3]
Hi @zqingr 

Thank you for the project, very cool stuff!!!

I get 404 on https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js for some reason.
should it be https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js?

Would like to contribute or collaborate if you are looking for help.

Dimitrius

**Comment by zqingr** [comment]
Hi @dimitrius1986 

Where did you get the link "https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js", I can't find this link in this project. 

If you want to contribute or collaborate, you can fork this project and send a pull request.

Thanks.

**Comment by dimitrius1986** [comment]
Hi,
Sorry It does 404 for https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map, my bad :)
But I also get Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.dtype') from tf-layers.esm.js:41 
Initially I thought it was because of 404.
it looks like Webpack not excluding node_modules, is it on purpose?

**Comment by zqingr** [comment]
Sorry, I still can't where did you get this error.
Is it during installation, startup or web page error?

https://github.com/zqingr/tfjs-yolov3-demo, This project is the source code of the demo. maybe it can help you :)

**Comment by dimitrius1986** [comment]
its on after i clone, npm install and npm start, on the 0.0.0.0:8000 i get Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.dtype') from tf-layers.esm.js:41

on https://github.com/zqingr/tfjs-yolov3-demo i get TypeError: Cannot read property 'loadLayersModel' of undefined

Sorry its probably something i'm doing... but i just clone, install and start

**Comment by zqingr** [comment]
I cloned it again, working fine after installation and startup.

What is your npm version? my npm version is 6.4.1, if your version is lower than this, you can try to upgrade your npm version. or you can try to install with yarn.

**Comment by zqingr** [comment]
I tried it again, really encountered the error you said. 

The reason for the error is the version of tfjs has been upgraded.
Actually, I don't know why we getting an error. It seems that something went wrong during the loading of the model. 

I think this is bug of tfjs, so, I just locked the version to 1.0.0. and you can try it again!

**Comment by dimitrius1986** [comment]
Yep, it works now :)

**Comment by dimitrius1986** [comment]
Hi,

Can I ask you couple of questions?
How did you get the models?  Did you use tf.js converter?
Have you tried to retrain the model? Where would you truncate it?

Thank you,
Dimitrius

**Comment by zqingr** [comment]
Hi,

Yes, I downloaded the cfg and weights from https://pjreddie.com/darknet/yolo/  and generated the model using the tfjs converter.

I have not tried retrain the model yet. But when I did similar training a year ago, I found that comparing js training with Python, its performance will be much worse, especially when training some deeper networks. It’s hard to train. So at the time I gave up the retrain on it. But I will take the time to try it out.



发件人: DIMITRIUS IONOV<mailto:notifications@github.com>
发送时间: 2019年3月28日 2:42
收件人: zqingr/tfjs-yolov3<mailto:tfjs-yolov3@noreply.github.com>
抄送: 韧青子<mailto:zqi@live.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [zqingr/tfjs-yolov3] 404 on https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map (#3)

Hi,

Can I ask you couple of questions?
How did you get the models? Did you use tf.js converter?
Have you tried to retrain the model? Where would you truncate it?

Thank you,
Dimitrius

**Comment by dimitrius1986** [comment]
Hi, Thank you for trying again.

I think it should be faster now with the nodejs-gpu support, what do you think?
I’m very new to machine learning and tenserflow, would you mind if I ask you couple of stupid questions?
For the optimizer would optimizer: tf.train.adam(0.001) work?
For the lossFunction would tf.tidy(() => noObjectLoss.add(objectLoss).add(coordLoss).add(classLoss)) work?
How does training work for yolo? Do I need to truncate the model, can I do transfer learning or for each model I have to train from scratch since anchors would be different..

Thank you,
Dimitrius Ionov

**Comment by zqingr** [comment]
Hi, Dimitrius.

I am sorry that I can't answer your question, because I am also a newcomer to machine learning.

I built this project at the time of reference https://github.com/qqwweee/keras-yolo3 , I had the same question with you at the time.
Although I translated into the js, I still don't know how it works. so I temporarily gave up studying machine learning and learning related mathematics first.
You can click on the link I just mentioned, it has training related things, you can look at it, hope it can help you.

Thank you,
Zi

https://github.com/qqwweee/keras-yolo3


________________________________
发件人: DIMITRIUS IONOV <notifications@github.com>
发送时间: Tuesday, April 2, 2019 7:34:03 AM
收件人: zqingr/tfjs-yolov3
抄送: 韧青子; State change
主题: Re: [zqingr/tfjs-yolov3] 404 on https://cdn.jsdelivr.net/npm/@tensorflow/tf.min.js.map (#3)

Hi, Thank you for trying again.

I think it should be faster now with the nodejs-gpu support, what do you think?
I’m very new to machine learning and tenserflow, would you mind if I ask you couple of stupid questions?
For the optimizer would optimizer: tf.train.adam(0.001) work?
For the lossFunction would tf.tidy(() => noObjectLoss.add(objectLoss).add(coordLoss).add(classLoss)) work?
How does training work for yolo? Do I need to truncate the model, can I do transfer learning or for each model I have to train from scratch since anchors would be different..

Thank you,
Dimitrius Ionov
